databases:
  - name: backoffice-db
    databaseName: backoffice_db
    user: backoffice_user

services:
  - type: web
    name: my-backoffice
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: backoffice-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: backoffice-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: backoffice-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: backoffice-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: backoffice-db
          property: database
      - key: NODE_ENV
        value: production